# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change
  
